config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'wods#index'
resources :wods
resources :timers
get '/heroes' => 'wods#hero_workouts'
get '/ladies' => 'wods#lady_workouts'
get 'weather', to: 'wods#weather'
resources :logs do
  resources :exercises
end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :log
end

app/models/log.rb
class Log < ApplicationRecord
  has_many :exercises, dependent: :destroy  
  belongs_to :user
  validates :date, presence: true
  validates :workout, presence: true
  validates :mood, presence: true
  validates :length, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :logs
end

app/models/wod.rb
class Wod < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def create
    @log = Log.find(params[:log_id])
    @exercise = @log.exercises.create(params[:exercise].permit(:title, :sets, :reps))

    redirect_to log_path(@log)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_log, only: [:show, :edit, :update, :destroy]  

  def index
    @logs = current_user.logs.order("created_at DESC")
  end

  def show
    
  end

  def new
    @log = Log.new
  end

  def create
    @log = current_user.logs.create(log_params)
    if @log.valid?
      redirect_to @log
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @log.update(log_params)
      redirect_to @log
    else
      render 'edit'
    end
  end

  def destroy
    @log.destroy
    redirect_to logs_path
  end


  private

  def log_params
    params.require(:log).permit(:date, :workout, :mood, :length)
  end

  def find_log
    @log = Log.find(params[:id])
  end



end

app/controllers/timers_controller.rb
class TimersController < ApplicationController

  def index
  end
end

app/controllers/wods_controller.rb
class WodsController < ApplicationController

  def index
    @wod = Wod.order("RANDOM()").first
  end

  def hero_workouts
     @wod = Wod.where(category: 'Heroes').order("RANDOM()").first 
     render template: "wods/heroes"
  end
  
  def lady_workouts
     @wod = Wod.where(category: 'Ladies').order("RANDOM()").first
     render template: "wods/ladies"
  end

  def weather
    render template: "wods/weather"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/timers_helper.rb
module TimersHelper
end

app/helpers/wods_helper.rb
module WodsHelper
end

app/views/exercises/_exercise.html.erb


<table class="table table-bordered">
  <thead>
    <tr class="table-head">
      <th scope="col">Exercise</th>
      <th scope="col">Sets</th>
      <th scope="col">Reps</th>
    </tr>
  </thead>
  <tbody>
     <% @log.exercises.each do |exercise| %>
     <tr>
      <td><%= exercise.title %></td>
      <td><%= exercise.sets %></td>
      <td><%= exercise.reps %></td>
    </tr>
    <% end %> 
  </tbody>
</table>

app/views/exercises/_form.html.erb
<div class="col-4 offset-4">
  <%= simple_form_for ([@log, @log.exercises.build]) do |f| %>
    <%= f.input :title, wrapper_html: { class: 'log_form' } %>
    <%= f.input :sets, wrapper_html: { class: 'log_form' } %>
    <%= f.input :reps, wrapper_html: { class: 'log_form' } %>
    <br />
    <%= f.submit 'Create' %>
  <% end %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WodGenerator</title>
    
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-light bg-transparent">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to "Wod Generator", root_path, class: "navbar-brand" %>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Timer", timers_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Workout Tracker", logs_path, class: "nav-link" %>
            </li>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                 <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'New Workout', new_log_path, class:'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Weather", weather_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </nav>
      <% if notice.present? %>  
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <div id="footer">
      <div class="container text-center">
        
        <%= link_to "Davis Development", "https://davisdevelopment.tech", :target => "_blank" %>
      </div>
    </div>
  </body>
</html>

app/views/logs/edit.html.erb
<h1>New Workout Log</h1>
<%= simple_form_for @log do |f| %>
  <%= f.input :date, wrapper_html: { class: 'log_form' } %>
  <%= f.input :workout, label: 'What did you workout?', wrapper_html: { class: 'log_form' } %>
  <%= f.input :mood, label: 'How were you feeling?', wrapper_html: { class: 'log_form' } %>
  <%= f.input :length, label: 'How long was the workout?', wrapper_html: { class: 'log_form' } %>
  <%= f.submit 'Update' %>
<% end %>

app/views/logs/index.html.erb
<h1 class="logtitle">Your Workouts</h1>
<br />
<% @logs.each do |log| %>
  <h2 class=" worklog text-center">
    <%= link_to log.date.strftime("%A %B %d"), log %><br />
    <%= log.workout %><br />
    <!--<%= log.mood %><br />
    <%= log.length %><br /><br /> -->
  </h2>
  <br />
<% end %>

  

app/views/logs/new.html.erb
<h1 class="new-workout text-center">New Workout Log</h1>
<div class=" entry col-8 offset-2">
<%= simple_form_for @log do |f| %>
  <%= f.input :date, wrapper_html: { class: 'log_form' } %>
  <%= f.input :workout, label: 'What did you workout?', wrapper_html: { class: 'log_form' } %>
  <%= f.input :mood, label: 'How were you feeling?', wrapper_html: { class: 'log_form' } %>
  <%= f.input :length, label: 'How long was the workout?', wrapper_html: { class: 'log_form' } %>
  <%= f.submit 'Create' %>
<% end %>
</div>


app/views/logs/show.html.erb
<div class="worklog text-center">
  <%= @log.date.strftime("%A %B %d") %><br />
  <%= @log.workout %><br />
  <%= @log.mood %><br />
  <%= @log.length %>
</div>

<div class="worklog">
  
  <%= render 'exercises/exercise' %>
  <h3 class="text-center">Add an exercise</h3>
  <%= render 'exercises/form' %>
</div>

<%= link_to 'Back', logs_path %>
<%= link_to 'Edit', edit_log_path(@log) %>
<%= link_to 'Delete', log_path(@log), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/timers/index.html.erb

<div class="box">
  <div class="text-center">
    <h1 id="timer"> 00 : 00 . 000 </h1>
  </div>
  <br />
  <button id="toggle" class='begin'>Start</button>
  <button id="reset">Reset</button>
</div>






app/views/wods/heroes.html.erb

<div class="row justify-content-center">
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body text-center">
        <h5 class="card-title"><%= @wod.title %></h5>
       <p class="card-text"><% @wod.description.each do |x| %>
          <%= x %><br />
        <% end %></p>
        <a href="/heroes" class="btn btn-primary">Randomize</a>
      </div>
    </div>
  </div>
</div>

<!-- dropdown menu -->
<div class="row justify-content-center"> 
  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Choose Your Fate
    <span class="caret"></span></button>
    <ul class="dropdown-menu text-center">
      <li><a href="/heroes">Hero</a></li>
      <li><a href="/ladies">The Ladies</a></li>
      <li><a href="/wods">Anything Goes</a></li>
    </ul>
  </div>
</div>




app/views/wods/index.html.erb

<div class="row justify-content-center">
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body text-center">
        <h5 class="card-title"><%= @wod.title %></h5>
       <p class="card-text"><% @wod.description.each do |x| %>
          <% if x.scan("run").length > 0 %>
           <a href="/weather" target="_blank">
              A run!! Check the Weather <br />
            </a>
          <% end %> 
          <%= x %><br />
        <% end %></p>
        <a href="/wods" class="btn btn-primary">Randomize</a>
      </div>
    </div>
  </div>
</div>

<!-- dropdown menu -->
<div class="row justify-content-center"> 
  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Choose Your Fate
    <span class="caret"></span></button>
    <ul class="dropdown-menu text-center">
      <li><a href="/heroes">Hero</a></li>
      <li><a href="/ladies">The Ladies</a></li>
      <li><a href="/wods">Anything Goes</a></li>
    </ul>
  </div>
</div>




app/views/wods/ladies.html.erb

<div class="row justify-content-center">
  <div class="col-sm-3">
    <div class="card">
      <div class="card-body text-center">
        <h5 class="card-title"><%= @wod.title %></h5>
       <p class="card-text"><% @wod.description.each do |x| %>
          <%= x %><br />
        <% end %></p>
        <a href="/ladies" class="btn btn-primary">Randomize</a>
      </div>
    </div>
  </div>
</div>

<!-- dropdown menu -->
<div class="row justify-content-center"> 
  <div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Choose Your Fate
    <span class="caret"></span></button>
    <ul class="dropdown-menu text-center">
      <li><a href="/heroes">Hero</a></li>
      <li><a href="/ladies">The Ladies</a></li>
      <li><a href="/wods">Anything Goes</a></li>
    </ul>
  </div>
</div>




app/views/wods/weather.html.erb
<div class="jumbotron">
  <i class="fas fa-running"></i>
  <h2 class=" jumboBanner text-center">Good Day to Run??</h2>
</div>
<div class="container text-center">
  <div class="row" >
    <div class="col-md-12 style margin-bottom:10px;">
      <h3 class="text-center text-primary">Enter City</h3>
       <span id="error" class="text-center"></span>
    </div>
    <div class="row form-group form-inline" id="cityDiv">
      <div class="col-md-12">
      <input type="text" name="city" id="city" class="form-control"  style margin-top:10px>
      <button id="submitCity" class="btn btn-primary">Search City</button>
    </div>     
    </div>
  </div>
  <div id="showWeather"></div>
</div>